apiVersion: apps/v1
kind: Deployment
metadata:
  name: donaton-frontend
  namespace: donaton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donaton-frontend
  template:
    metadata:
      labels:
        app: donaton-frontend
    spec:
      containers:
        - name: donaton-frontend
          image: 063406728315.dkr.ecr.us-east-1.amazonaws.com/donaton-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
